server:
  port: 8080

DB_ADDRESS: "localhost"
DB_PORT: "3306"
DB_USER: "root"
DB_PASSWORD: "password"

spring:
  resources:
    static-locations: classpath:/static
  mvc:
    view:
      prefix: /
      suffix: .html
  datasource:
    url: jdbc:mysql://${DB_ADDRESS}:${DB_PORT}/musicDB?useUnicode=true&characterEncoding=utf8
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect

logging:
  level:
    com.akvone: DEBUG
    org.springframework: INFO